### ISSUE TITLE
Let error when I run the task

### ISSUE THREAD

**Issue by luiguild** [terinjokes/gulp-uglify#228]
I have this gulp task:

```
gulp.task('make:js', function (cb) {
    pump([
        gulp.src(files.js.src),
        $.concat(app.name + '.js'),
        jsValidate(),
        uglify({
            mangle: false
        }),
        $.rename(function (path) {
            path.basename += '.min';
        }),
        gulp.dest(files.js.dest)
    ], cb);
});
```

And my JS file is:
```
var a = 1;
let b = 2;
```

If I declare my vars using "let" rather than "var", my task brokes and my log error is:
```
Message:
    /Applications/.../js/timeline.js: SyntaxError: Unexpected token: name (b)
Details:
    fileName: /Applications/.../timeline.js
    lineNumber: 2
```

Anyone already seen the same thing or something about this?
